color_list = ['snow', 'gainsboro', 'peach puff',
    'lemon chiffon','lavender','dark slate gray', 'gray', 'light grey',
    'lemon chiffon','lavender','dark slate gray', 'gray', 'light grey',
    'midnight blue','cornflower blue', 'dark slate blue',
    'medium slate blue', 'medium blue', 'royal blue',  'blue',
    'deep sky blue', 'sky blue', 'light sky blue', 'steel blue', 'light steel blue',
    'light blue', 'pale turquoise', 'dark turquoise', 'turquoise',
    'cyan', 'light cyan', 'cadet blue', 'medium aquamarine', 'aquamarine', 'dark green', 'dark olive green',
    'dark sea green', 'sea green', 'medium sea green', 'light sea green', 'pale green', 'spring green',
    'lawn green', 'medium spring green', 'green yellow', 'lime green', 'yellow green',
    'forest green', 'olive drab', 'dark khaki', 'khaki', 'pale goldenrod',
    'light yellow', 'yellow', 'gold', 'light goldenrod', 'dark goldenrod', 'rosy brown',
    'indian red', 'saddle brown', 'sandy brown',
    'dark salmon', 'salmon', 'light salmon',
    'orange', 'dark orange',
    'coral', 'light coral', 'tomato', 'orange red', 'red',
    'hot pink', 'deep pink', 'pink', 'light pink',
    'pale violet red', 'maroon',
    'medium violet red', 'violet red',
    'medium orchid', 'dark orchid',
    'dark violet', 'blue violet',
    'purple', 'medium purple',
    'thistle',
    'snow2', 'snow4',
    'seashell2', 'seashell4',
    'AntiqueWhite1', 'AntiqueWhite4',
    'bisque2', 'bisque4',
    'PeachPuff2','PeachPuff4',
    'NavajoWhite2','NavajoWhite4',
    'LemonChiffon2', 'LemonChiffon4',
    'cornsilk2', 'cornsilk4',
    'ivory2', 'ivory4',
    'honeydew2', 'honeydew4',
    'LavenderBlush2', 'LavenderBlush4',
    'MistyRose2', 'MistyRose4',
    'azure2', 'azure4',
    'SlateBlue1', 'SlateBlue4',
    'RoyalBlue1', 'RoyalBlue4',
    'blue2', 'blue4',
    'DodgerBlue2', 'DodgerBlue4',
    'SteelBlue1', 'SteelBlue4',
    'DeepSkyBlue2', 'DeepSkyBlue4',
    'SkyBlue1',  'SkyBlue4',
    'LightSkyBlue1', 'LightSkyBlue4',
    'SlateGray1', 'SlateGray4',
    'LightSteelBlue1', 'LightSteelBlue4',
    'LightBlue1', 'LightBlue4',
    'LightCyan1', 'LightCyan4',
    'PaleTurquoise1','PaleTurquoise4',
    'CadetBlue1', 'CadetBlue4',
    'turquoise1', 'turquoise4',
    'cyan2','cyan4',
    'DarkSlateGray1', 'DarkSlateGray4',
    'aquamarine2', 'aquamarine4',
    'DarkSeaGreen1', 'DarkSeaGreen4',
    'SeaGreen1', 'SeaGreen3',
    'PaleGreen1', 'PaleGreen4',
    'SpringGreen2', 'SpringGreen4',
    'green2', 'green4',
    'chartreuse2', 'chartreuse4',
    'OliveDrab1', 'OliveDrab4',
    'DarkOliveGreen1', 'DarkOliveGreen4',
    'khaki1', 'khaki4',
    'LightGoldenrod1', 'LightGoldenrod4',
    'LightYellow2', 'LightYellow4',
    'yellow2', 'yellow4',
    'gold1', 'gold4',
    'RosyBrown1','RosyBrown4',
    'IndianRed1', 'IndianRed4',
    'sienna1', 'sienna4',
    'burlywood1','burlywood4',
    'wheat1','wheat4',
    'tan1','tan4',
    'chocolate1','chocolate3',
    'firebrick1','firebrick4',
    'brown1','brown4',
    'salmon1','salmon4',
    'LightSalmon2', 'LightSalmon4',
    'orange2','orange4',
    'DarkOrange1','DarkOrange4',
    'coral1','coral4',
    'tomato2', 'tomato4',
    'OrangeRed2','OrangeRed4',
    'red2','red4',
    'DeepPink2', 'DeepPink4',
    'HotPink1','HotPink4',
    'pink1', 'pink4',
    'LightPink1','LightPink4',
    'PaleVioletRed1','PaleVioletRed4',
    'maroon1','maroon4',
    'VioletRed1','VioletRed4',
    'magenta2','magenta4',
    'orchid1', 'orchid4',
    'plum1','plum4',
    'MediumOrchid1', 'MediumOrchid4',
    'DarkOrchid1', 'DarkOrchid4',
    'purple1',  'purple4',
    'MediumPurple1','MediumPurple4',
    'thistle1',  'thistle4',
    'gray99']